# Generated by Django 4.1.2 on 2022-12-05 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gateway', '0002_alter_jwt_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jwt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
