# Generated by Django 4.1.2 on 2022-12-05 21:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gateway', '0006_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jwt1',
            new_name='Jwt',
        ),
    ]
