# Generated by Django 4.1.2 on 2022-12-06 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0007_rename_jwt1_jwt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Jwt',
        ),
    ]
