# Generated by Django 4.1.2 on 2022-12-06 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0009_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Jwt',
        ),
    ]
