# Generated by Django 4.1.2 on 2022-12-01 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=150, verbose_name='Category name')),
                ('category_description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=150, verbose_name='Post Title')),
                ('created_date', models.DateTimeField()),
                ('updated_on', models.DateTimeField()),
                ('post_contents', models.TextField()),
                ('post_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiapp.postcategory', verbose_name='Post Category')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
